/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Oprincipio.Cliente;

import br.Oprincipio.Bean.Cliente_Bean;
import br.Oprincipio.DAO.Cliente_DAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class JF_CadastroCliente extends javax.swing.JFrame {

    List<Cliente_Bean> clientes;
    boolean existente;

    /**
     * Creates new form Cadastro_JF
     *
     * @param c
     */
    public JF_CadastroCliente(Cliente_Bean c) {
        initComponents();
        iniciaFrm();
        testarCliente(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cdSpinner = new javax.swing.JSpinner();
        nomelbl = new javax.swing.JTextField();
        cpflbl = new javax.swing.JFormattedTextField();
        telefonelbl = new javax.swing.JTextField();
        emaillbl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        anivertf = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        novolbl = new javax.swing.JLabel();
        procurarlbl = new javax.swing.JLabel();
        gravarlbl = new javax.swing.JLabel();
        cancelarlbl = new javax.swing.JLabel();
        excluirlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefone");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("E-Mail");

        cdSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        try {
            cpflbl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpflbl.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Aniversário");

        try {
            anivertf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        anivertf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        anivertf.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomelbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cdSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpflbl, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(telefonelbl))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anivertf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addComponent(emaillbl))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cdSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(anivertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cpflbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefonelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(emaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        novolbl.setBackground(new java.awt.Color(255, 255, 255));
        novolbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        novolbl.setForeground(new java.awt.Color(255, 255, 255));
        novolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        novolbl.setText("Novo");
        novolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novolblMouseClicked(evt);
            }
        });

        procurarlbl.setBackground(new java.awt.Color(255, 255, 255));
        procurarlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        procurarlbl.setForeground(new java.awt.Color(255, 255, 255));
        procurarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procurarlbl.setText("Procurar");
        procurarlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarlblMouseClicked(evt);
            }
        });

        gravarlbl.setBackground(new java.awt.Color(255, 255, 255));
        gravarlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gravarlbl.setForeground(new java.awt.Color(255, 255, 255));
        gravarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gravarlbl.setText("Gravar");
        gravarlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gravarlblMouseClicked(evt);
            }
        });

        cancelarlbl.setBackground(new java.awt.Color(255, 255, 255));
        cancelarlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelarlbl.setForeground(new java.awt.Color(255, 255, 255));
        cancelarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarlbl.setText("Cancelar");
        cancelarlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarlblMouseClicked(evt);
            }
        });

        excluirlbl.setBackground(new java.awt.Color(255, 255, 255));
        excluirlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        excluirlbl.setForeground(new java.awt.Color(255, 255, 255));
        excluirlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        excluirlbl.setText("Excluir");
        excluirlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirlblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(novolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(procurarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(gravarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(cancelarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(excluirlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procurarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gravarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novolblMouseClicked
        novo();
    }//GEN-LAST:event_novolblMouseClicked

    private void procurarlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarlblMouseClicked
        procurar();
    }//GEN-LAST:event_procurarlblMouseClicked

    private void gravarlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gravarlblMouseClicked
        gravar();
    }//GEN-LAST:event_gravarlblMouseClicked

    private void cancelarlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarlblMouseClicked
        cancelar();
    }//GEN-LAST:event_cancelarlblMouseClicked

    private void excluirlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirlblMouseClicked
        excluir();
    }//GEN-LAST:event_excluirlblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_CadastroCliente(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField anivertf;
    private javax.swing.JLabel cancelarlbl;
    private javax.swing.JSpinner cdSpinner;
    private javax.swing.JFormattedTextField cpflbl;
    private javax.swing.JTextField emaillbl;
    private javax.swing.JLabel excluirlbl;
    private javax.swing.JLabel gravarlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nomelbl;
    private javax.swing.JLabel novolbl;
    private javax.swing.JLabel procurarlbl;
    private javax.swing.JTextField telefonelbl;
    // End of variables declaration//GEN-END:variables
    private void iniciaFrm() {
        statusLbls(false);
        statusBtnInicial();
        try {
            clientes = new Cliente_DAO().findAll();
        } catch (Exception ex) {
            Logger.getLogger(JF_CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void statusLbls(boolean status) {
        cdSpinner.setEnabled(status);
        nomelbl.setEnabled(status);
        cpflbl.setEnabled(status);
        telefonelbl.setEnabled(status);
        emaillbl.setEnabled(status);
        anivertf.setEnabled(status);
    }

    private void statusBtn(boolean status) {
        novolbl.setVisible(status);
        procurarlbl.setVisible(status);
        gravarlbl.setVisible(status);
        cancelarlbl.setVisible(status);
        excluirlbl.setVisible(status);
    }

    private void limparLbls() {
        nomelbl.setText("");
        cpflbl.setText("");
        telefonelbl.setText("");
        emaillbl.setText("");
        anivertf.setText("");
    }

    private void statusBtnInicial() {
        limparLbls();
        statusLbls(false);
        novolbl.setVisible(true);
        procurarlbl.setVisible(true);
        gravarlbl.setVisible(false);
        cancelarlbl.setVisible(false);
        excluirlbl.setVisible(false);
    }

    private void testarCliente(Cliente_Bean c) {
        if (c != null) {
            cdSpinner.setValue(c.getId());
            nomelbl.setText(c.getNome());
            cpflbl.setText(c.getCpf());
            telefonelbl.setText(c.getTelefone());
            emaillbl.setText(c.getEmail());
            anivertf.setText(c.getAniversario(c.BR));
            existente = true;
            statusBtn(true);
            novolbl.setVisible(false);
            statusLbls(true);
            cdSpinner.setEnabled(false);
        }
    }

    private void gravar() {
        try {
            Cliente_Bean nv = new Cliente_Bean();
            nv.setNome(nomelbl.getText());
            if (!cpflbl.getText().equals("   .   .   -  ")) {
                nv.setCpf(cpflbl.getText());
            }
            if (!telefonelbl.getText().equals("")) {
                nv.setTelefone(telefonelbl.getText());
            }
            if (!emaillbl.getText().equals("")) {
                nv.setEmail(emaillbl.getText());
            }
            if (!anivertf.getText().equals("  /  /    ")) {
                nv.setAniversario(anivertf.getText(), nv.BR);
            }
            if (!existente) {
                if (new Cliente_DAO().insertInto(nv)) {
                    JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
                    statusBtnInicial();
                    clientes = new Cliente_DAO().findAll();
                }
            } else if (existente) {
                nv.setId((int) cdSpinner.getValue());
                if (new Cliente_DAO().update(nv)) {
                    JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");
                    statusBtnInicial();
                    clientes = new Cliente_DAO().findAll();
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JF_CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao Gravar", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void novo() {
        int max = 0;
        for (Cliente_Bean c : clientes) {
            if (c.getId() > max) {
                max = c.getId();
            }
        }
        max++;
        cdSpinner.setValue(max);
        statusLbls(true);
        cdSpinner.setEnabled(false);
        statusBtn(false);
        gravarlbl.setVisible(true);
        cancelarlbl.setVisible(true);
        existente = false;
    }

    private void procurar() {
        JF_BuscaCliente fm = new JF_BuscaCliente();
        fm.setVisible(true);
        this.dispose();
    }

    private void cancelar() {
        limparLbls();
        statusLbls(false);
        statusBtnInicial();
        existente = false;
    }

    private void excluir() {
        if (existente) {
            int op = -1;
            op = JOptionPane.showOptionDialog(null, "Deseja realmente excluir esse cliente?\nCaso tenha valores em aberto tudo sera apagado!", "Exclusão Segura", JOptionPane.YES_NO_CANCEL_OPTION, 1, null, null, null);
            if (op == 0) {
                if (new Cliente_DAO().delete((int) cdSpinner.getValue())) {
                    JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Falha ao tentar excluir cliente do banco de dados!");
                }
            }
        }
        statusBtnInicial();
    }
}
