/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Oprincipio.Boleto;

import br.Oprincipio.Bean.Banco_Bean;
import br.Oprincipio.Bean.Boleto_Bean;
import br.Oprincipio.Bean.Fornecedor_Bean;
import br.Oprincipio.DAO.Boleto_DAO;
import br.Oprincipio.DAO.Fornecedor_DAO;
import funcoes.AutoCompletion;
import funcoes.Conv;
import funcoes.ScroollJTable;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class JF_Boleto extends javax.swing.JFrame {

    int localValor = 9;
    DefaultTableModel tb;

    /**
     * Creates new form Boleto_JF
     */
    public JF_Boleto() {
        initComponents();
        this.setExtendedState(JF_Boleto.MAXIMIZED_BOTH);
        AutoCompletion.enable(jComboBoxFornecedor);
        tb = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter<>(tb));
        atualizarTB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        inicio = new javax.swing.JFormattedTextField();
        fim = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CheckBoxPagos = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        cd_barras_leitor = new javax.swing.JTextField();
        atualizar_info_btn = new javax.swing.JButton();
        jComboBoxFornecedor = new javax.swing.JComboBox<>();
        vencimento_boleto_txt = new javax.swing.JFormattedTextField();
        lancar_boleto_btn = new javax.swing.JButton();
        valor_boleto_txt = new javax.swing.JTextField();
        bancotxt = new javax.swing.JTextField();
        buscar_fornecedor_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        valorTotalEmAbertotxt = new javax.swing.JTextField();
        valorAbertotxt = new javax.swing.JTextField();
        totalLinhas = new javax.swing.JLabel();
        totalLinhasAberto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Boletos");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setAutoscrolls(true);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vencimento", "Fornecedor", "Valor", "Pago", "Código de Barras", "Marcar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.util.Date.class, java.lang.Object.class, java.lang.Double.class, java.util.Date.class, java.lang.Object.class,java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(1).setMinWidth(80);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(80);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(6).setMinWidth(40);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(40);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Filtro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        try {
            inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inicio.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        inicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inicioKeyPressed(evt);
            }
        });

        try {
            fim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fim.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        fim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fimActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 177, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Data Inicial");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("Data Final");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        CheckBoxPagos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CheckBoxPagos.setText("Pagos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fim)
            .addComponent(inicio, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(CheckBoxPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(CheckBoxPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Lançar Boleto"));

        cd_barras_leitor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cd_barras_leitor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cd_barras_leitor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cd_barras_leitorKeyPressed(evt);
            }
        });

        atualizar_info_btn.setBackground(new java.awt.Color(0, 0, 0));
        atualizar_info_btn.setForeground(new java.awt.Color(255, 255, 255));
        atualizar_info_btn.setText("Atualizar");
        atualizar_info_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_info_btnActionPerformed(evt);
            }
        });

        jComboBoxFornecedor.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxFornecedor.setMaximumRowCount(1000);
        jComboBoxFornecedor.setToolTipText("");

        try {
            vencimento_boleto_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vencimento_boleto_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vencimento_boleto_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vencimento_boleto_txtKeyPressed(evt);
            }
        });

        lancar_boleto_btn.setBackground(new java.awt.Color(0, 0, 0));
        lancar_boleto_btn.setForeground(new java.awt.Color(255, 255, 255));
        lancar_boleto_btn.setText("Lançar");
        lancar_boleto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancar_boleto_btnActionPerformed(evt);
            }
        });

        valor_boleto_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor_boleto_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valor_boleto_txtKeyPressed(evt);
            }
        });

        bancotxt.setEditable(false);

        buscar_fornecedor_btn.setBackground(new java.awt.Color(0, 0, 0));
        buscar_fornecedor_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/application_view_list.png"))); // NOI18N
        buscar_fornecedor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_fornecedor_btnActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Código de Barras");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fornecedor");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Banco");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vencimento");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arrow_left.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arrow_right.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cd_barras_leitor)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vencimento_boleto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(valor_boleto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFornecedor, 0, 490, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(buscar_fornecedor_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(atualizar_info_btn)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bancotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lancar_boleto_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cd_barras_leitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bancotxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizar_info_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscar_fornecedor_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valor_boleto_txt)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vencimento_boleto_txt)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lancar_boleto_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Baixar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jButton2.setBackground(new java.awt.Color(210, 137, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Selecionado(s)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(210, 137, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Todos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Alterar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jButton4.setBackground(new java.awt.Color(230, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(230, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TOTAL em aberto");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Em aberto na tabela");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        valorTotalEmAbertotxt.setEditable(false);
        valorTotalEmAbertotxt.setBackground(new java.awt.Color(255, 255, 255));
        valorTotalEmAbertotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorTotalEmAbertotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorTotalEmAbertotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTotalEmAbertotxtActionPerformed(evt);
            }
        });

        valorAbertotxt.setEditable(false);
        valorAbertotxt.setBackground(new java.awt.Color(255, 255, 255));
        valorAbertotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valorAbertotxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        totalLinhas.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        totalLinhas.setText("Total de Linhas Exibidas: ");

        totalLinhasAberto.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        totalLinhasAberto.setText("Total de Linhas em Aberto: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(valorTotalEmAbertotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valorAbertotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totalLinhas, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(totalLinhasAberto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(valorTotalEmAbertotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(valorAbertotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLinhas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLinhasAberto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inicioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioKeyPressed

    private void fimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizarTB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cd_barras_leitorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cd_barras_leitorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            analisarCodigoDeBarras(cd_barras_leitor.getText());
        }
    }//GEN-LAST:event_cd_barras_leitorKeyPressed

    private void atualizar_info_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar_info_btnActionPerformed
        buscar_fornecedor();
    }//GEN-LAST:event_atualizar_info_btnActionPerformed

    private void vencimento_boleto_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vencimento_boleto_txtKeyPressed

    }//GEN-LAST:event_vencimento_boleto_txtKeyPressed

    private void lancar_boleto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancar_boleto_btnActionPerformed
        salvarBoleto();
    }//GEN-LAST:event_lancar_boleto_btnActionPerformed

    private void valor_boleto_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_boleto_txtKeyPressed

    }//GEN-LAST:event_valor_boleto_txtKeyPressed

    private void buscar_fornecedor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_fornecedor_btnActionPerformed
        String codigo = cd_barras_leitor.getText();
        if (codigo.length()==47){
            analisarCodigoDeBarras(cd_barras_leitor.getText());
        }
        if (codigo.length() == 44) {
            try {
                Boleto_Bean b = new Boleto_Bean();
                b.setAll(codigo);
                JD_BuscaFornecedorBanco jd = new JD_BuscaFornecedorBanco(this, true, b.getBanco(), b.getCd_barras());
                jd.setVisible(true);
                jComboBoxFornecedor.removeAllItems();
                jComboBoxFornecedor.addItem(jd.fornecedor_retorno);
            } catch (Exception ex) {
                Logger.getLogger(JF_Boleto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buscar_fornecedor_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        baixar_selecionado();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        baixar_todos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        editarBoleto();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jTable1.getSelectedRow() >= 0) {
            excluir();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void valorTotalEmAbertotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTotalEmAbertotxtActionPerformed

    }//GEN-LAST:event_valorTotalEmAbertotxtActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        clickNaTabela();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        valorMenos();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        valorMais();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Boleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Boleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxPagos;
    private javax.swing.JButton atualizar_info_btn;
    private javax.swing.JTextField bancotxt;
    private javax.swing.JButton buscar_fornecedor_btn;
    private javax.swing.JTextField cd_barras_leitor;
    private javax.swing.JFormattedTextField fim;
    private javax.swing.JFormattedTextField inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBoxFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lancar_boleto_btn;
    private javax.swing.JLabel totalLinhas;
    private javax.swing.JLabel totalLinhasAberto;
    private javax.swing.JTextField valorAbertotxt;
    private javax.swing.JTextField valorTotalEmAbertotxt;
    private javax.swing.JTextField valor_boleto_txt;
    private javax.swing.JFormattedTextField vencimento_boleto_txt;
    // End of variables declaration//GEN-END:variables

    private void analisarCodigoDeBarras(String codigo) {
        try {
            Boleto_Bean b = new Boleto_Bean();
            b.setAll(codigo);
            bancotxt.setText(Integer.toString(b.getBanco()));
            vencimento_boleto_txt.setText(b.getVencimento());
            valor_boleto_txt.setText(Conv.validarValue(b.getValor()));
            cd_barras_leitor.setText(b.getCd_barras());
            buscar_fornecedor();
            if (jComboBoxFornecedor.getItemCount() == 0) {
                JD_BuscaFornecedorBanco jd = new JD_BuscaFornecedorBanco(this, true, b.getBanco(), b.getCd_barras());
                jd.setVisible(true);
                jComboBoxFornecedor.removeAllItems();
                jComboBoxFornecedor.addItem(jd.fornecedor_retorno);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Erro", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }

    private void valorMenos() {
        if (cd_barras_leitor.getText().length() != 44 && cd_barras_leitor.getText().length() != 47) {
            JOptionPane.showMessageDialog(null, "Algo esta errado com o código de barras.\nTamanho esperado: 44 ou 47.\nTamanho informado: " + cd_barras_leitor.getText().length());
        }
        String cd_barras = cd_barras_leitor.getText();
        if (cd_barras.length() == 47) {
            String temp = "";
            temp = temp + cd_barras.substring(0, 4);
            temp = temp + cd_barras.substring(32);
            temp = temp + cd_barras.substring(4, 9);
            temp = temp + cd_barras.substring(10, 20);
            temp = temp + cd_barras.substring(21, 31);
            cd_barras = temp;
        }
        localValor++;
        double valor = Double.parseDouble(cd_barras.substring(localValor, 10 + localValor)) / 100;
        valor_boleto_txt.setText(Conv.validarValue(valor));
    }

    private void valorMais() {
        if (cd_barras_leitor.getText().length() != 44 && cd_barras_leitor.getText().length() != 47) {
            JOptionPane.showMessageDialog(null, "Algo esta errado com o código de barras.\nTamanho esperado: 44 ou 47.\nTamanho informado: " + cd_barras_leitor.getText().length());
        }
        String cd_barras = cd_barras_leitor.getText();
        if (cd_barras.length() == 47) {
            String temp = "";
            temp = temp + cd_barras.substring(0, 4);
            temp = temp + cd_barras.substring(32);
            temp = temp + cd_barras.substring(4, 9);
            temp = temp + cd_barras.substring(10, 20);
            temp = temp + cd_barras.substring(21, 31);
            cd_barras = temp;
        }
        localValor--;
        double valor = Double.parseDouble(cd_barras.substring(localValor, 10 + localValor)) / 100;
        valor_boleto_txt.setText(Conv.validarValue(valor));
    }

    private void buscar_fornecedor() {
        String cd = cd_barras_leitor.getText();
        jComboBoxFornecedor.removeAllItems();
        if (cd.length() != 44) {
            return;
        }
        List<Fornecedor_Bean> fornecedores = new Fornecedor_DAO().findAll();
        for (Fornecedor_Bean f : fornecedores) {
            for (Banco_Bean b : f.getBanco()) {
                if (b.getNumero() != null) {
                    if (cd.contains(b.getNumero())) {
                        jComboBoxFornecedor.addItem(f.getNome());
                    }
                }
            }
        }
    }

    private void salvarBoleto() {
        if (cd_barras_leitor.getText().length() == 44) {
            List<Fornecedor_Bean> fornecedores = new Fornecedor_DAO().getFornecedoresSeco();
            Fornecedor_Bean f = null;
            for (Fornecedor_Bean forn : fornecedores) {
                if (forn.getNome().equals(jComboBoxFornecedor.getItemAt(jComboBoxFornecedor.getSelectedIndex()))) {
                    f = forn;
                }
            }
            List<Boleto_Bean> boletos = new Boleto_DAO().findAll();
            for (Boleto_Bean b : boletos) {
                if (b.getCd_barras().equals(cd_barras_leitor.getText())) {
                    JOptionPane.showMessageDialog(null, "Código de boleto já lançado", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (f != null) {
                Boleto_Bean b = new Boleto_Bean();
                b.setCd_barras(cd_barras_leitor.getText());
                b.setBanco(Integer.parseInt(bancotxt.getText()));
                b.setVencimento(vencimento_boleto_txt.getText());
                b.setValor(Conv.CDblDuasCasas(Double.parseDouble(valor_boleto_txt.getText().replaceAll(",", "\\."))));
                b.setFornecedor(f);
                if (!new Boleto_DAO().addBoleto(b)) {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar salvar o boleto.", "ERRO", JOptionPane.ERROR_MESSAGE);
                } else {
                    atualizarTB();
                    limparTXTS();
                    int maior = 0;
                    int value = 0;
                    for (int x = 0; x < jTable1.getRowCount(); x++) {
                        if ((int) jTable1.getValueAt(x, 0) > value) {
                            value = (int) jTable1.getValueAt(x, 0);
                            maior = x;
                        }
                    }
                    jTable1.setRowSelectionInterval(maior, maior);
                    ScroollJTable.scrollToVisible(jTable1, maior);
                }
            }
        }
    }

    private void atualizarTB() {
        tb.setRowCount(0);
        List<Boleto_Bean> boletos = new Boleto_DAO().findAll();
        for (Boleto_Bean b : boletos) {
            //"Sequencia", "Vencimento", "Fornecedor_Bean", "Valor", "Pago", "Código de Barras", "Marcar"
            Date vencimento, pago = null;
            SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
            try {
                vencimento = form.parse(b.getVencimento());
            } catch (ParseException ex) {
                vencimento = null;
                Logger.getLogger(JF_Boleto.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (b.getPago() != null) {
                try {
                    pago = form.parse(b.getPago());
                } catch (ParseException ex) {
                    Logger.getLogger(JF_Boleto.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                pago = null;
            }
            Object[] dado = {b.getId(), vencimento, b.getFornecedor().getNome(), b.getValor(), pago, b.getCd_barras(), null};
            if (inicio.getText().equals("  /  /    ") && fim.getText().equals("  /  /    ")) {
                if (CheckBoxPagos.isSelected()) {
                    tb.addRow(dado);
                } else if (pago == null) {
                    tb.addRow(dado);
                }
            } else {
                Date dboleto = vencimento;
                Date ini;
                Date fi;
                try {
                    ini = form.parse(inicio.getText());
                    fi = form.parse(fim.getText());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Filtro de datas inválidos.");
                    return;
                }
                if (dboleto.compareTo(ini) >= 0 && dboleto.compareTo(fi) <= 0) {
                    if (CheckBoxPagos.isSelected()) {
                        tb.addRow(dado);
                    } else if (pago == null) {
                        tb.addRow(dado);
                    }
                }
            }
        }
        total_em_aberto();
        total_em_aberto_tabela();
        totalLinhas.setText("Total de Linhas Exibidas: "+tb.getRowCount());
    }

    public void limparTXTS() {
        cd_barras_leitor.setText("");
        jComboBoxFornecedor.removeAllItems();
        bancotxt.setText("");
        vencimento_boleto_txt.setText("");
        valor_boleto_txt.setText("");
        cd_barras_leitor.requestFocus();
    }

    private void clickNaTabela() {
        if (jTable1.getSelectedRow() < 0) {
            return;
        }
        if (jTable1.getValueAt(jTable1.getSelectedRow(), 6) == null) {
            jTable1.setValueAt("X", jTable1.getSelectedRow(), 6);
        } else {
            jTable1.setValueAt(null, jTable1.getSelectedRow(), 6);
        }
    }

    private void baixar_selecionado() {
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            if (jTable1.getValueAt(x, 6) != null) {
                if (!new Boleto_DAO().pagarBoleto((int) jTable1.getValueAt(x, 0))) {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar dar baixa no boleto.");
                    return;
                }
            }
        }
        atualizarTB();
    }

    private void baixar_todos() {
        int op = -1;
        op = JOptionPane.showOptionDialog(this, "Deseja realmente sinalizar como pago todos os boletos exibidos na tabela?", "Confirmação de Segurança.", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        if (op == 0) {
            for (int x = 0; x < jTable1.getRowCount(); x++) {
                if (!new Boleto_DAO().pagarBoleto((int) jTable1.getValueAt(x, 0))) {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar dar baixa no boleto.");
                    return;
                }
            }
            atualizarTB();
        }
    }

    private void total_em_aberto() {
        List<Boleto_Bean> total = new Boleto_DAO().findAll();
        double valor = 0;
        for (Boleto_Bean b : total) {
            if (b.getPago() == null) {
                valor += b.getValor();
            }
        }
        valorTotalEmAbertotxt.setText(Conv.colocarPontoEmValor(Conv.validarValue(valor)));
    }

    private void total_em_aberto_tabela() {
        double valor = 0;
        int count =0;
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            if (jTable1.getValueAt(x, 4) == null) {
                valor += (double) jTable1.getValueAt(x, 3);
                count++;
            }
        }
        valorAbertotxt.setText(Conv.colocarPontoEmValor(Conv.validarValue(valor)));
        totalLinhasAberto.setText("Total de Linhas em Aberto: "+count);
    }

    private void editarBoleto() {
        if (jTable1.getSelectedRow() >= 0) {
            int id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            JD_EditarBoleto jd = new JD_EditarBoleto(this, true, id);
            jd.setVisible(true);
            atualizarTB();
        }
    }

    private void excluir() {
        int op = -1;
        op = JOptionPane.showOptionDialog(this, "Deseja realmente excluir o boleto selecionado?", "Confirmação de exclusão", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        if (op != 0) {
            return;
        }
        int id = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        if (!new Boleto_DAO().deletarBoleto(id)){
            JOptionPane.showMessageDialog(null, "Erro ao tentar deletar boleto!","Erro",JOptionPane.ERROR_MESSAGE);
        }else{
            atualizarTB();
        }
    }
}
