package br.Oprincipio.Menu;

//import br.OPrincipio.Bean.Caixa;
import br.Oprincipio.Bean.Caixa_Bean;
import br.Oprincipio.Bean.Cliente_Bean;
import br.Oprincipio.Bean.Usuario_Bean;
import br.Oprincipio.Boleto.JF_Boleto;
import br.Oprincipio.Cliente.JD_CadastroCliente;
import br.Oprincipio.Cliente.JF_CrediarioCliente;
import br.Oprincipio.ContasOutros.JF_ContasOutras;
import br.Oprincipio.DAO.Boleto_DAO;
import br.Oprincipio.DAO.Caixa_DAO;
import br.Oprincipio.Fornecedor.JF_Fornecedor;
import br.Oprincipio.PDV.JF_PDV;
import br.Oprincipio.Produto.JF_EntradaEstoque;
import br.Oprincipio.DAO.Cliente_DAO;
import br.Oprincipio.DAO.Conta_DAO;
import br.Oprincipio.Movimento.JF_CancelarMovimento;
import br.Oprincipio.Movimento.JF_ImprimirMovimento;
import br.Oprincipio.Movimento.RelatorioVendas;
import br.Oprincipio.PDV.JD_AbrirFecharCaixa;
import br.Oprincipio.PDV.JF_AbrirFecharCaixa;
import br.Oprincipio.Produto.JF_CadastroCombo;
import br.Oprincipio.Produto.JF_CadastroProduto;
import br.Oprincipio.Produto.RelatorioEstoque;
import br.Oprincipio.Usuario.JD_Login;
import br.Oprincipio.Usuario.JF_Usuario;
import funcoes.CDate;
import funcoes.Conv;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    JF_PDV pdv;
    Caixa_Bean caixa;
    Usuario_Bean usuario;

    /**
     * Creates new form Menu_JF
     */
    public Menu() {
        initComponents();
        atualizarJTA();
        caixa = null;
        usuario = null;
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        usuariotxt = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O Princípio");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Smile and Wave", 0, 150)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logo2.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jta.setColumns(20);
        jta.setRows(5);
        jta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_menu_18px.png"))); // NOI18N
        jMenu4.setText("Opções");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_settings_power_24px.png"))); // NOI18N
        jMenuItem11.setText("Sair");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/layers-3.png"))); // NOI18N
        jMenu1.setText("PDV");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_desktop_mac_24px.png"))); // NOI18N
        jMenuItem1.setText("Caixa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/settings-gear-63.png"))); // NOI18N
        jMenuItem15.setText("Abre/Fecha Caixa");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/single-01.png"))); // NOI18N
        jMenuItem16.setText("Logar");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/multiple-11.png"))); // NOI18N
        jMenu2.setText("Pessoas/Empresas");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/single-01.png"))); // NOI18N
        jMenuItem2.setText("Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_assistant_photo_24px.png"))); // NOI18N
        jMenuItem4.setText("Crediário");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator4);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_store_24px.png"))); // NOI18N
        jMenuItem7.setText("Fornecedor");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator5);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/single-01.png"))); // NOI18N
        jMenuItem8.setText("Usuário");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_shopping_cart_24px.png"))); // NOI18N
        jMenu3.setText("Produtos");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_local_pizza_24px.png"))); // NOI18N
        jMenuItem3.setText("Produtos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);
        jMenu3.add(jSeparator1);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/gift-2.png"))); // NOI18N
        jMenuItem6.setText("Combos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_shopping_basket_24px.png"))); // NOI18N
        jMenu5.setText("Estoque");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/single-folded-content.png"))); // NOI18N
        jMenuItem10.setText("Entradas Estoque");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/handout.png"))); // NOI18N
        jMenuItem13.setText("Devolução Mercadorias");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_assessment_24px.png"))); // NOI18N
        jMenu6.setText("Contas");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_keyboard_arrow_right_24px.png"))); // NOI18N
        jMenuItem9.setText("Boletos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_keyboard_arrow_right_24px.png"))); // NOI18N
        jMenuItem12.setText("Outras Contas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/notes.png"))); // NOI18N
        jMenu7.setText("Relatório");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/ic_monetization_on_24px.png"))); // NOI18N
        jMenuItem14.setText("Relatório de Vendas");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem14);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/archive-2.png"))); // NOI18N
        jMenuItem5.setText("Relatório de Estoque");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1x/single-folded-content.png"))); // NOI18N
        jMenuItem17.setText("Imprimir Movimento");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem17);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //br.OPrincipio.Cliente_Bean.JF_CadastroProduto jf = new br.OPrincipio.Cliente_Bean.JF_CadastroProduto(null);
        JD_CadastroCliente jf = new JD_CadastroCliente(null, true, null);
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JF_CadastroProduto jf = new JF_CadastroProduto(null);
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (usuario == null) {
            System.out.println("PDV:: usuario null");
            JOptionPane.showMessageDialog(null, "Sem usuário logado.", "Login", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (caixa == null) {
            System.out.println("PDV:: caixa null");
            if (new Caixa_DAO().verificarSeEstaEmAberto()) {
                Caixa_Bean caixa_temp = new Caixa_DAO().getCaixaAberto();
                if (caixa_temp.getUsuario().getId() == usuario.getId()) {
                    caixa = caixa_temp;
                    System.out.println("PDV:: caixa null, porem verificado e visto que tem caixa aberto.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Caixa fechado.", "Caixa", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (new Caixa_DAO().verificarSeEstaEmAberto()) {
            System.out.println("PDV :: tem caixa aberto");
            if (new Caixa_DAO().getCaixaAberto().getUsuario().getId() != usuario.getId()) {
                System.out.println("PDV:: caixa em aberto com usuario diferente");
                JOptionPane.showMessageDialog(null, "Já existe um caixa aberto com outro usuário.", "Erro", JOptionPane.INFORMATION_MESSAGE);
            } else {
                System.out.println("PDV:: caixa em aberto com usuario igual");
                pdv = new JF_PDV(usuario, caixa);
                pdv.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum caixa aberto.", "Erro desconhecido", JOptionPane.ERROR_MESSAGE);
            System.out.println("PDV:: algo fez entrar no else");
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JF_CrediarioCliente jf = new JF_CrediarioCliente();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        RelatorioEstoque jf = new RelatorioEstoque();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JF_CadastroCombo jf = new JF_CadastroCombo(null);
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JF_Fornecedor jf = new JF_Fornecedor();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JF_Usuario jf = new JF_Usuario();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        JF_Boleto jf = new JF_Boleto();
        jf.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JF_EntradaEstoque jf = new JF_EntradaEstoque();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jtaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaFocusGained
        atualizarJTA();
    }//GEN-LAST:event_jtaFocusGained

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        JF_ContasOutras jf = new JF_ContasOutras();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        JF_CancelarMovimento jf = new JF_CancelarMovimento();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        RelatorioVendas jf = new RelatorioVendas();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        if (usuario == null) {      //nao foi logado nenhum usuario ainda
            jMenuItem16ActionPerformed(null);
        }
        if (usuario != null) {      //caso a opção de cima esteja sido executada e mesmo assim o usuario saiu sem logar
            if (new Caixa_DAO().verificarSeEstaEmAberto()) {
                Caixa_Bean caixa_temp = new Caixa_DAO().getCaixaAberto();
                System.out.println("Abri/fecha:: tem caixa aberto, usuario atual logado: " + usuario.getNome() + " usuario do caixa logado: " + caixa_temp.getUsuario().getNome());
                if (caixa_temp.getUsuario().getId() != usuario.getId()) { //tem caixa aberto e mesmo usuario
                    JOptionPane.showMessageDialog(null, "Existe outro usuário com caixa aberto.", "Erro", JOptionPane.INFORMATION_MESSAGE);
                    caixa = null;
                } else {
                    JD_AbrirFecharCaixa jd = new JD_AbrirFecharCaixa(null, true, usuario);
                    jd.setVisible(true);
                    if (jd.getUsuario() == null) {
                        usuario = null;
                        usuariotxt.setText("");
                    } else {
                        usuario = jd.getUsuario();
                    }
                    if (jd.getCaixa() == null) {
                        caixa = null;
                    } else {
                        caixa = jd.getCaixa();
                    }
                }

            } else {        //nao tem nenhum caixa aberto
                JD_AbrirFecharCaixa jd = new JD_AbrirFecharCaixa(null, true, usuario);
                jd.setVisible(true);
                if (jd.getUsuario() == null) {
                    usuario = null;
                    usuariotxt.setText("");
                } else {
                    usuario = jd.getUsuario();
                }
                if (jd.getCaixa() == null) {
                    caixa = null;
                } else {
                    caixa = jd.getCaixa();
                }
            }
        }

    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        JD_Login jd = new JD_Login(null, true);
        jd.setVisible(true);
        if (jd.getUsuario() != null) {
            usuario = jd.getUsuario();
            usuariotxt.setText(usuario.getNome());
            System.out.println("LOGIN :: realizado login com " + usuario.getNome());
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        JF_ImprimirMovimento jf = new JF_ImprimirMovimento();
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTextArea jta;
    private javax.swing.JLabel usuariotxt;
    // End of variables declaration//GEN-END:variables

    private void getAniversarios() {
        try {
            List<Cliente_Bean> clientes = new Cliente_DAO().findAll();
            for (Cliente_Bean c : clientes) {
                Date cli = c.getAniversarioDate();
                if (cli != null) {
                    Calendar clicalendar = Calendar.getInstance();
                    clicalendar.setTime(cli);
                    clicalendar.set(Calendar.getInstance().get(Calendar.YEAR), clicalendar.get(Calendar.MONTH), clicalendar.get(Calendar.DAY_OF_MONTH));
                    //System.out.println("Cliente_Bean :" + c.getNome() + "  " + clicalendar.get(Calendar.DAY_OF_MONTH) + "/" + clicalendar.get(Calendar.MONTH) + "/" + clicalendar.get(Calendar.YEAR));
                    Date test = null;
                    try {
                        test = CDate.DataPTBRStringToDate(CDate.DataPTBRAtual());
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    cli = clicalendar.getTime();
                    if (cli.equals(test)) {
                        jta.append(c.aniversarioHoje() + "\n");
                    }
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getContasHoje() {
        jta.append("Valor de boletos em aberto Hoje: " + Conv.colocarPontoEmValor(Double.toString(Conv.CDblDuasCasas(new Boleto_DAO().getContasHoje())).replaceAll("\\.", ",")) + "\n");
        jta.append("Valor de outras contas em aberto: " + Conv.colocarPontoEmValor(Double.toString(Conv.CDblDuasCasas(new Conta_DAO().getTotalAberto())).replaceAll("\\.", ",")) + "\n");
    }

    private void atualizarJTA() {
        jta.setText(null);
        getAniversarios();
        getContasHoje();
        Calendar calendario = Calendar.getInstance();
        int hora, minuto, segundo;
        hora = calendario.get(Calendar.HOUR);
        minuto = calendario.get(Calendar.MINUTE);
        segundo = calendario.get(Calendar.SECOND);
        String h, m, s;
        if (hora < 10) {
            h = "0" + hora;
        } else {
            h = "" + hora;
        }
        if (minuto < 10) {
            m = "0" + minuto;
        } else {
            m = "" + minuto;
        }
        if (segundo < 10) {
            s = "0" + segundo;
        } else {
            s = "" + segundo;
        }
        jta.append("Ultima atualização: " + h + ":" + m + ":" + s);
    }
}
