/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Oprincipio.PDV;

import br.Oprincipio.Bean.Caixa_Bean;
import br.Oprincipio.Bean.Cliente_Bean;
import br.Oprincipio.Bean.POS_Bean;
import br.Oprincipio.Bean.Parcela;
import br.Oprincipio.Cliente.JD_BuscaCliente;
import br.Oprincipio.Bean.Venda_Bean;
import br.Oprincipio.DAO.Venda_DAO;
import br.Oprincipio.Bean.Produto_Bean;
import br.Oprincipio.DAO.Caixa_DAO;
import br.Oprincipio.DAO.Parcela_JD;
import funcoes.CDate;
import funcoes.Conv;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JD_FinalizarCompraPDV extends javax.swing.JDialog {

    DefaultTableModel tb;

    public double total;
    public double total_temp;

    public double f_dinheiro;
    public double f_credito;
    public double f_debito;
    public double f_crediario;
    public double f_desconto;
    public double f_troco;
    public int f_parcela_credito;
    public int f_parcela_debito;
    private POS_Bean pos;

    public Cliente_Bean cliente;
    public int mov;

    public int fim;
    private int seq;

    /**
     * Creates new form Finalizar_JD
     *
     * @param parent
     * @param modal
     * @param valor
     * @param tb_
     * @param movimento
     */
    public JD_FinalizarCompraPDV(java.awt.Frame parent, boolean modal, double valor, DefaultTableModel tb_, int movimento,int seq_) {
        super(parent, modal);
        initComponents();
        tb = tb_;
        mov = movimento;
        total = valor;
        total_temp = total;
        totaltxt.setText(Conv.validarValue(valor));
        restantetf.setText(Conv.validarValue(valor));
        f_dinheiro = 0;
        f_credito = 0;
        f_debito = 0;
        f_crediario = 0;
        f_desconto = 0;
        f_troco = 0;
        seq = seq_;
        itensCounttxt.setText(Integer.toString(tb.getRowCount()));
        movtxt.setText(Integer.toString(movimento));
        fim = 0;
        pos = new POS_Bean();
        try {
            cliente = new Cliente_Bean();
            cliente.setId(1);
            cliente.setNome("Consumidor Final");
            clientetf.setText(cliente.getNome());
        } catch (Exception ex) {
            Logger.getLogger(JD_FinalizarCompraPDV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dinheiroBtn = new javax.swing.JButton();
        POS_CreditoBtn = new javax.swing.JButton();
        POS_Debito_Btn = new javax.swing.JButton();
        crediarioBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        totaltxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        restantetf = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        trocotf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        descBtn = new javax.swing.JButton();
        desctf = new javax.swing.JTextField();
        clientetf = new javax.swing.JTextField();
        alterarClienteBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        movtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itensCounttxt = new javax.swing.JTextField();
        finalizarBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        d_txt = new javax.swing.JTextField();
        cred_txt = new javax.swing.JTextField();
        desc_txt = new javax.swing.JTextField();
        creditoJC = new javax.swing.JComboBox<>();
        debitoJC = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forma de Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        dinheiroBtn.setBackground(new java.awt.Color(0, 153, 0));
        dinheiroBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dinheiroBtn.setText("Dinheiro");
        dinheiroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiroBtnActionPerformed(evt);
            }
        });
        dinheiroBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dinheiroBtnKeyPressed(evt);
            }
        });

        POS_CreditoBtn.setBackground(new java.awt.Color(255, 153, 0));
        POS_CreditoBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        POS_CreditoBtn.setText("POS Crédito");
        POS_CreditoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POS_CreditoBtnActionPerformed(evt);
            }
        });
        POS_CreditoBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                POS_CreditoBtnKeyPressed(evt);
            }
        });

        POS_Debito_Btn.setBackground(new java.awt.Color(255, 153, 0));
        POS_Debito_Btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        POS_Debito_Btn.setText("POS Débito");
        POS_Debito_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POS_Debito_BtnActionPerformed(evt);
            }
        });
        POS_Debito_Btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                POS_Debito_BtnKeyPressed(evt);
            }
        });

        crediarioBtn.setBackground(new java.awt.Color(204, 0, 0));
        crediarioBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crediarioBtn.setText("Crediário");
        crediarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crediarioBtnActionPerformed(evt);
            }
        });
        crediarioBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crediarioBtnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dinheiroBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(POS_CreditoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addComponent(POS_Debito_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addComponent(crediarioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(dinheiroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(POS_CreditoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(POS_Debito_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crediarioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        totaltxt.setEditable(false);
        totaltxt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totaltxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totaltxt)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totaltxt)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Restante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        restantetf.setEditable(false);
        restantetf.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        restantetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restantetf)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(restantetf)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Troco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        trocotf.setEditable(false);
        trocotf.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        trocotf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trocotf)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trocotf)
        );

        jLabel1.setText("Cliente");

        descBtn.setBackground(new java.awt.Color(0, 102, 102));
        descBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        descBtn.setText("DESC.");
        descBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descBtnActionPerformed(evt);
            }
        });

        desctf.setEditable(false);
        desctf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        desctf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clientetf.setEditable(false);

        alterarClienteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/arrow_refresh.png"))); // NOI18N
        alterarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Mov.");

        movtxt.setEditable(false);

        jLabel3.setText("Itens");

        itensCounttxt.setEditable(false);

        finalizarBtn.setBackground(new java.awt.Color(0, 0, 204));
        finalizarBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        finalizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        finalizarBtn.setText("Finalizar");
        finalizarBtn.setEnabled(false);
        finalizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarBtnActionPerformed(evt);
            }
        });
        finalizarBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                finalizarBtnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientetf, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alterarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(finalizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itensCounttxt)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(movtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(desctf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descBtn))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(desctf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(clientetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alterarClienteBtn))
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(itensCounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalizarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dinheiro");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("POS Crédito");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("POS Débito");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Crediário");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Desconto");

        d_txt.setEditable(false);

        cred_txt.setEditable(false);

        desc_txt.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creditoJC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(debitoJC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cred_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(cred_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(desc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(creditoJC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(debitoJC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(d_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dinheiroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiroBtnActionPerformed
        f_dinheiro += valorDadoAoCaixa();
        atualizarValoresLbls();
    }//GEN-LAST:event_dinheiroBtnActionPerformed

    private void POS_CreditoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POS_CreditoBtnActionPerformed
        Parcela_JD jd = new Parcela_JD(null, true);                             //JDialog retornando numero de parcelas
        jd.setVisible(true);
        if (jd.getParcela()==0){
            return;
        }
        int n_parcelas = jd.getParcela();
        JD_LancarValor jd2 = new JD_LancarValor(null, true, total_temp / n_parcelas); //JDialog retornando valor de cada parcela
        jd2.setVisible(true);
        if (jd2.getValor()==0){
            return;
        }
        double valor_parcela = jd2.getValor();

        f_credito += valor_parcela * n_parcelas;
        creditoJC.addItem(n_parcelas + "x" + Conv.validarValue(valor_parcela)); //acrecentado no JCombo a informação das parcelas
        for (int i=0;i<n_parcelas;i++){
            pos.addParcela(CDate.SomarData_MES(i+1, CDate.DataPTBRAtual()), valor_parcela);
        }
        atualizarValoresLbls();
    }//GEN-LAST:event_POS_CreditoBtnActionPerformed

    private void POS_Debito_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POS_Debito_BtnActionPerformed
        Parcela_JD jd = new Parcela_JD(null, true);                             //JDialog retornando numero de parcelas
        jd.setVisible(true);
        if (jd.getParcela()==0){
            return;
        }
        int n_parcelas = jd.getParcela();
        JD_LancarValor jd2 = new JD_LancarValor(null, true, total_temp / n_parcelas); //JDialog retornando valor de cada parcela
        jd2.setVisible(true);
        if (jd2.getValor()==0){
            return;
        }
        double valor_parcela = jd2.getValor();
        
        f_debito += valor_parcela * n_parcelas;
        debitoJC.addItem(n_parcelas + "x" + Conv.validarValue(valor_parcela));
        for (int i=0;i<n_parcelas;i++){
            pos.addParcela(CDate.SomarData_MES(i+1, CDate.DataPTBRAtual()), valor_parcela);
        }
        atualizarValoresLbls();
    }//GEN-LAST:event_POS_Debito_BtnActionPerformed

    private void dinheiroBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinheiroBtnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            POS_CreditoBtn.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dinheiroBtnActionPerformed(null);
        }
    }//GEN-LAST:event_dinheiroBtnKeyPressed

    private void POS_CreditoBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_POS_CreditoBtnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            POS_Debito_Btn.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            dinheiroBtn.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            POS_CreditoBtnActionPerformed(null);
        }
    }//GEN-LAST:event_POS_CreditoBtnKeyPressed

    private void POS_Debito_BtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_POS_Debito_BtnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            crediarioBtn.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            POS_CreditoBtn.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            POS_Debito_BtnActionPerformed(null);
        }
    }//GEN-LAST:event_POS_Debito_BtnKeyPressed

    private void crediarioBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crediarioBtnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            POS_Debito_Btn.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            crediarioBtnActionPerformed(null);
        }
    }//GEN-LAST:event_crediarioBtnKeyPressed

    private void crediarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crediarioBtnActionPerformed
        JD_BuscaCliente jd = new JD_BuscaCliente(null, true,false);
        jd.setVisible(true);
        if (jd.cliente != null) {
            cliente = jd.cliente;
            clientetf.setText(cliente.getNome());
            double valorLancar = valorDadoAoCaixa();
            if (valorLancar > 0) {
                cliente = jd.cliente;
                f_crediario += valorLancar;
                alterarClienteBtn.setEnabled(false);
            }
        }
        atualizarValoresLbls();
    }//GEN-LAST:event_crediarioBtnActionPerformed

    private void descBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descBtnActionPerformed
        desconto();
    }//GEN-LAST:event_descBtnActionPerformed

    private void alterarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteBtnActionPerformed
        JD_BuscaCliente jd = new JD_BuscaCliente(null, true,false);
        jd.setVisible(true);
        if (jd.cliente != null) {
            cliente = jd.cliente;
            clientetf.setText(cliente.getNome());
        }

    }//GEN-LAST:event_alterarClienteBtnActionPerformed

    private void finalizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarBtnActionPerformed
        if (mov == -1) {
            System.exit(0);
            return;
        }
        finalizar();
    }//GEN-LAST:event_finalizarBtnActionPerformed

    private void finalizarBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_finalizarBtnKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            finalizarBtnActionPerformed(null);
        }
    }//GEN-LAST:event_finalizarBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_FinalizarCompraPDV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_FinalizarCompraPDV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_FinalizarCompraPDV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_FinalizarCompraPDV.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_FinalizarCompraPDV dialog = new JD_FinalizarCompraPDV(new javax.swing.JFrame(), true, 50, new DefaultTableModel(), -1, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton POS_CreditoBtn;
    private javax.swing.JButton POS_Debito_Btn;
    private javax.swing.JButton alterarClienteBtn;
    private javax.swing.JTextField clientetf;
    private javax.swing.JTextField cred_txt;
    private javax.swing.JButton crediarioBtn;
    private javax.swing.JComboBox<String> creditoJC;
    private javax.swing.JTextField d_txt;
    private javax.swing.JComboBox<String> debitoJC;
    private javax.swing.JButton descBtn;
    private javax.swing.JTextField desc_txt;
    private javax.swing.JTextField desctf;
    private javax.swing.JButton dinheiroBtn;
    private javax.swing.JButton finalizarBtn;
    private javax.swing.JTextField itensCounttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField movtxt;
    private javax.swing.JTextField restantetf;
    private javax.swing.JTextField totaltxt;
    private javax.swing.JTextField trocotf;
    // End of variables declaration//GEN-END:variables

    private void setStatusBtn(boolean status) {
        dinheiroBtn.setEnabled(status);
        POS_CreditoBtn.setEnabled(status);
        POS_Debito_Btn.setEnabled(status);
        crediarioBtn.setEnabled(status);
        descBtn.setEnabled(status);
        if (!status) {
            finalizarBtn.setEnabled(true);
            finalizarBtn.requestFocus();
        }
    }

    private double valorDadoAoCaixa() {
        JD_LancarValor jd = new JD_LancarValor(null, true, total_temp);
        jd.setVisible(true);
        return jd.getValor();
    }

    private void finalizar() {
        Venda_Bean v = new Venda_Bean();
        v.setPago(!(f_crediario > 0.0));
        v.setCliente(cliente);
        v.setMovimento(mov);
        v.setDinheiro(f_dinheiro);
        
        pos.setMovimento(mov);
        double total_cartao_parcela=0;
        total_cartao_parcela = pos.getParcela().stream().map((p) -> p.getValor()).reduce(total_cartao_parcela, (accumulator, _item) -> accumulator + _item);
        pos.setTotal(total_cartao_parcela);
        v.setPos(pos);
        
        v.setPOS_credito(f_credito);
        v.setPOS_debito(f_debito);
        v.setCrediario(f_crediario);
        v.setDesconto(f_desconto);

        v.setTotal(total);
        v.setTroco(f_troco);
        v.setData(CDate.DataPTBRAtual());
        List<Produto_Bean> produtos = new ArrayList<>();
        for (int x = 0; x < tb.getRowCount(); x++) {
            Produto_Bean p = new Produto_Bean();
            try {
                p.setCodigo((String) tb.getValueAt(x, 2));
            } catch (Exception ex) {
                Logger.getLogger(JD_FinalizarCompraPDV.class.getName()).log(Level.SEVERE, null, ex);
            }
            p.setDescricao((String) tb.getValueAt(x, 1));
            p.setVenda((double) tb.getValueAt(x, 4));
            p.setQuantidade((double) tb.getValueAt(x, 3));
            produtos.add(p);
        }
        v.setProdutos(produtos);
        Caixa_Bean caixa = new Caixa_Bean();
        caixa.setSeq(seq);
        caixa.setDinheiro(f_dinheiro);
        caixa.setCrediario(f_crediario);
        caixa.setDebito(f_debito);
        caixa.setCredito(f_credito);
        
        if (new Venda_DAO().insertInto(v) && new Venda_DAO().baixarEstoque(v) && new Caixa_DAO().addinfoCaixa(caixa)) {
            fim = 1;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "ERRO ao tentar lançar");
        }
    }

    private void desconto() {
        JD_DescontoPDV jd = new JD_DescontoPDV(null, true);
        jd.setVisible(true);
        if (jd.tipo == 1) {
            double valorTotal = total;
            valorTotal = valorTotal * jd.v - valorTotal;
            f_desconto = valorTotal;
        } else if (jd.tipo == 2) {
            f_desconto = jd.v;
        }
        atualizarValoresLbls();
    }

    public void atualizarValoresLbls() {
        d_txt.setText(Conv.validarValue(f_dinheiro));
        cred_txt.setText(Conv.validarValue(f_crediario));
        desc_txt.setText(Conv.validarValue(f_desconto));

        total_temp = total;
        total_temp -= (f_dinheiro + f_crediario + f_credito + f_debito + f_desconto);
        f_troco = 0;

        if (total_temp < 0) {
            f_troco = total_temp * (-1);
            total_temp = 0;
        }
        trocotf.setText(Conv.validarValue(f_troco));
        restantetf.setText(Conv.validarValue(total_temp));
        if (total_temp == 0) {
            setStatusBtn(false);
        }
    }

}
