/*
 * Copyright (c) 2019, User
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package br.Oprincipio.PDV;

import br.Oprincipio.Bean.Caixa_Bean;
import br.Oprincipio.Bean.Usuario_Bean;
import br.Oprincipio.DAO.Caixa_DAO;
import br.Oprincipio.DAO.Usuario_DAO;
import br.Oprincipio.DAO.Venda_DAO;
import funcoes.CDate;
import funcoes.Conv;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class JF_AbrirFecharCaixa extends javax.swing.JFrame {

    private Usuario_Bean usuario;
    private Caixa_Bean caixa;

    private boolean abrirBoolean = false;

    /**
     * Creates new form JF_AbrirFecharCaixa
     *
     * @param u
     */
    public JF_AbrirFecharCaixa(Usuario_Bean u) {
        initComponents();
        usuario = u;
        caixa =null;
        iniciar(u);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        abrirbtn = new javax.swing.JButton();
        fecharbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fundotxt = new javax.swing.JTextField();
        dinheiro_txt = new javax.swing.JTextField();
        dinheiro_sistematxt = new javax.swing.JTextField();
        pos_sistematxt = new javax.swing.JTextField();
        postxt = new javax.swing.JTextField();
        crediario_sistematxt = new javax.swing.JTextField();
        crediariotxt = new javax.swing.JTextField();
        total_sistematxt = new javax.swing.JTextField();
        totaltxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        abrirbtn.setText("Abrir Caixa");
        abrirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirbtnActionPerformed(evt);
            }
        });

        fecharbtn.setText("Fechar Caixa");
        fecharbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharbtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Fundo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Dinheiro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("POS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Crediário");

        fundotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fundotxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fundotxt.setText("0");

        dinheiro_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dinheiro_txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dinheiro_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dinheiro_txtFocusLost(evt);
            }
        });
        dinheiro_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dinheiro_txtKeyPressed(evt);
            }
        });

        dinheiro_sistematxt.setEditable(false);
        dinheiro_sistematxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dinheiro_sistematxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        pos_sistematxt.setEditable(false);
        pos_sistematxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pos_sistematxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        postxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        postxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                postxtFocusLost(evt);
            }
        });
        postxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                postxtKeyPressed(evt);
            }
        });

        crediario_sistematxt.setEditable(false);
        crediario_sistematxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crediario_sistematxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        crediariotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crediariotxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        crediariotxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                crediariotxtFocusLost(evt);
            }
        });
        crediariotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crediariotxtKeyPressed(evt);
            }
        });

        total_sistematxt.setEditable(false);
        total_sistematxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_sistematxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        totaltxt.setEditable(false);
        totaltxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaltxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dinheiro_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pos_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crediario_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crediariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fundotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dinheiro_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fundotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dinheiro_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dinheiro_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pos_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crediario_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crediariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_sistematxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(abrirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fecharbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecharbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirbtnActionPerformed
        concluir();
    }//GEN-LAST:event_abrirbtnActionPerformed

    private void fecharbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharbtnActionPerformed
        concluir();
    }//GEN-LAST:event_fecharbtnActionPerformed

    private void dinheiro_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinheiro_txtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            somar_total();
            postxt.requestFocus();
        }
    }//GEN-LAST:event_dinheiro_txtKeyPressed

    private void crediariotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crediariotxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            somar_total();
        }
    }//GEN-LAST:event_crediariotxtKeyPressed

    private void postxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            somar_total();
            crediariotxt.requestFocus();
        }
    }//GEN-LAST:event_postxtKeyPressed

    private void dinheiro_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dinheiro_txtFocusLost
        somar_total();
    }//GEN-LAST:event_dinheiro_txtFocusLost

    private void postxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postxtFocusLost
        somar_total();
    }//GEN-LAST:event_postxtFocusLost

    private void crediariotxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_crediariotxtFocusLost
        somar_total();
    }//GEN-LAST:event_crediariotxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AbrirFecharCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AbrirFecharCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AbrirFecharCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AbrirFecharCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_AbrirFecharCaixa(new Usuario_DAO().getUsuario("JONATHAN")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirbtn;
    private javax.swing.JTextField crediario_sistematxt;
    private javax.swing.JTextField crediariotxt;
    private javax.swing.JTextField dinheiro_sistematxt;
    private javax.swing.JTextField dinheiro_txt;
    private javax.swing.JButton fecharbtn;
    private javax.swing.JTextField fundotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField pos_sistematxt;
    private javax.swing.JTextField postxt;
    private javax.swing.JTextField total_sistematxt;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables

    private void iniciar(Usuario_Bean u) {
        if (new Caixa_DAO().verificarSeEstaEmAberto()) {
            abrirbtn.setEnabled(false);
            fecharbtn.setEnabled(true);
            carregarCaixaAberto();
        } else {
            fecharbtn.setEnabled(false);
            abrirbtn.setEnabled(true);
            somenteFundo();
            setUsuario(u);
        }

    }

    private void carregarCaixaAberto() {
        caixa = new Caixa_DAO().getCaixaAberto();
        fundotxt.setEnabled(false);
        setCaixa(caixa);
        setUsuario(getCaixa().getUsuario());
        fundotxt.setText(Conv.validarValue(getCaixa().getFundo()));
        dinheiro_sistematxt.setText(Conv.validarValue(getCaixa().getDinheiro()));
        pos_sistematxt.setText(Conv.validarValue(getCaixa().getCredito() + getCaixa().getDebito()));
        crediario_sistematxt.setText(Conv.validarValue(getCaixa().getCrediario()));
        total_sistematxt.setText(Conv.validarValue(getCaixa().getDinheiro() + getCaixa().getCredito() + getCaixa().getDebito() + getCaixa().getCrediario()));
    }

    private void concluir() {
        if (abrirbtn.isEnabled()) { //concluir ação de abrir caixa
            abrir();
        } else {   //concluir ação de fechar o caixa
            fechar();
        }
    }

    private void somenteFundo() {
        dinheiro_sistematxt.setEnabled(false);
        dinheiro_txt.setEnabled(false);
        pos_sistematxt.setEnabled(false);
        postxt.setEnabled(false);
        crediario_sistematxt.setEnabled(false);
        crediariotxt.setEnabled(false);
        total_sistematxt.setEnabled(false);
        totaltxt.setEnabled(false);
    }

    private void abrir() {
        double fundo = 0;
        if (!fundotxt.getText().equals("")) {
            fundo = Double.parseDouble(fundotxt.getText().replaceAll(",", "\\."));
        }
        if (new Caixa_DAO().abrirCaixa(usuario, new Venda_DAO().getMovimentoLivre(), CDate.DataPTBRAtual(), fundo)) {
            abrirBoolean = true;
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao tentar abrir o caixa.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fechar() {
        double dinheiro = 0, pos = 0, crediario = 0;
        if (!"".equals(dinheiro_txt.getText())) {
            dinheiro = Double.parseDouble(dinheiro_txt.getText().replaceAll(",", "\\."));
        }
        if (!"".equals(postxt.getText())) {
            pos = Double.parseDouble(postxt.getText().replaceAll(",", "\\."));
        }
        if (!"".equals(crediariotxt.getText())) {
            crediario = Double.parseDouble(crediariotxt.getText().replaceAll(",", "\\."));
        }
        if (!new Caixa_DAO().fecharCaixa(caixa, dinheiro, pos, crediario)) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar fechar caixa.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Caixa fechado...");
            System.out.println("caixa fechado... anulando usuario e caixa");
            usuario = null;
            caixa = null;
            this.dispose();
        }
    }

    private void somar_total() {
        double d = 0, p = 0, c = 0;
        if (!"".equals(dinheiro_txt.getText())) {
            d = Double.parseDouble(dinheiro_txt.getText().replaceAll(",", "\\."));
        }
        if (!"".equals(postxt.getText())) {
            p = Double.parseDouble(postxt.getText().replaceAll(",", "\\."));
        }
        if (!"".equals(crediariotxt.getText())) {
            c = Double.parseDouble(crediariotxt.getText().replaceAll(",", "\\."));
        }
        totaltxt.setText(Double.toString(d + p + c));
    }

    /**
     * @return the usuario
     */
    public Usuario_Bean getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(Usuario_Bean usuario) {
        this.usuario = usuario;
    }

    /**
     * @return the caixa
     */
    public Caixa_Bean getCaixa() {
        return caixa;
    }

    /**
     * @param caixa the caixa to set
     */
    public void setCaixa(Caixa_Bean caixa) {
        this.caixa = caixa;
    }

    /**
     * @return the abrirBoolean
     */
    public boolean isAbrirBoolean() {
        return abrirBoolean;
    }

    /**
     * @param abrirBoolean the abrirBoolean to set
     */
    public void setAbrirBoolean(boolean abrirBoolean) {
        this.abrirBoolean = abrirBoolean;
    }
}
