/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Oprincipio.PDV;

import br.Oprincipio.Bean.Caixa_Bean;
import br.Oprincipio.Bean.Cliente_Bean;
import br.Oprincipio.DAO.Cliente_DAO;
import br.Oprincipio.Ireport.ImprimirIreport;
import br.Oprincipio.DAO.Venda_DAO;
import br.Oprincipio.Bean.Produto_Bean;
import br.Oprincipio.Bean.Usuario_Bean;
import br.Oprincipio.DAO.Caixa_DAO;
import br.Oprincipio.DAO.Produto_DAO;
import br.Oprincipio.DAO.Usuario_DAO;
import funcoes.Conv;
import funcoes.ScroollJTable;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JF_PDV extends javax.swing.JFrame {

    //Caixa caixa;
    List<Cliente_Bean> clientes;
    List<Produto_Bean> produtos;
    DefaultTableModel tb;
    int movimento;
    double totalAberto;

    double sangria;
    double suprimento;
    double fundo;
    Usuario_Bean usuario;
    Caixa_Bean caixa;
    String ip_conectado;

    /**
     * Creates new form PDV_JF
     *
     * @param usuario_
     * @param caixa_
     */
    public JF_PDV(Usuario_Bean usuario_, Caixa_Bean caixa_) {
        initComponents();
        this.usuario = usuario_;
        Caixa_Bean nv = new Caixa_Bean();
        nv.setSeq(caixa_.getSeq());
        this.caixa = nv;
        ini();
        iniciar_PDV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        qtdtxt = new javax.swing.JTextField();
        cdtxt = new javax.swing.JTextField();
        desctxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        finalizarBtn = new javax.swing.JButton();
        CancelarBtn = new javax.swing.JButton();
        BuscaBtn = new javax.swing.JButton();
        AtualizarBtn = new javax.swing.JButton();
        sangriaSuprimentoBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        valorTotallbl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        movtxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usertxt = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quantidade");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descrição");

        qtdtxt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        qtdtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtdtxt.setText("1");
        qtdtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtdtxtKeyPressed(evt);
            }
        });

        cdtxt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cdtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cdtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cdtxtKeyPressed(evt);
            }
        });

        desctxt.setEditable(false);
        desctxt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        desctxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desctxt)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qtdtxt)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdtxt)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(qtdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desctxt)
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sequencia", "Descrição", "Código", "Quantidade", "V. Unitário", "V. Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(26);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(2).setMinWidth(150);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(4).setMinWidth(100);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        finalizarBtn.setBackground(new java.awt.Color(220, 0, 0));
        finalizarBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        finalizarBtn.setText("Finalizar");
        finalizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarBtnActionPerformed(evt);
            }
        });

        CancelarBtn.setBackground(new java.awt.Color(200, 95, 2));
        CancelarBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelarBtn.setText("Cancelar");
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });

        BuscaBtn.setBackground(new java.awt.Color(220, 196, 0));
        BuscaBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BuscaBtn.setText("Buscar");
        BuscaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaBtnActionPerformed(evt);
            }
        });

        AtualizarBtn.setBackground(new java.awt.Color(255, 248, 137));
        AtualizarBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AtualizarBtn.setText("Atualizar");
        AtualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarBtnActionPerformed(evt);
            }
        });

        sangriaSuprimentoBtn.setBackground(new java.awt.Color(255, 255, 228));
        sangriaSuprimentoBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        sangriaSuprimentoBtn.setText("Sangria / Suprimento");
        sangriaSuprimentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sangriaSuprimentoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finalizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CancelarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(BuscaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AtualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sangriaSuprimentoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finalizarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AtualizarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sangriaSuprimentoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "VALOR TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        valorTotallbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        valorTotallbl.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valorTotallbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorTotallbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Movimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        movtxt.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        movtxt.setForeground(new java.awt.Color(255, 255, 255));
        movtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(movtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Gerar Cupom");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        usertxt.setForeground(new java.awt.Color(255, 255, 255));
        usertxt.setText("Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usertxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usertxt)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cdtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cdtxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            finalizarBtnActionPerformed(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            incluir_na_tabela();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            qtdtxt.setText("");
            qtdtxt.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F6) {
            CancelarBtnActionPerformed(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            BuscaBtnActionPerformed(null);
        }
    }//GEN-LAST:event_cdtxtKeyPressed

    private void qtdtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtdtxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cdtxt.requestFocus();
        }
    }//GEN-LAST:event_qtdtxtKeyPressed

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        excluir_item();
    }//GEN-LAST:event_CancelarBtnActionPerformed

    private void finalizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarBtnActionPerformed
        finalizar();
    }//GEN-LAST:event_finalizarBtnActionPerformed

    private void BuscaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaBtnActionPerformed
        buscar();
    }//GEN-LAST:event_BuscaBtnActionPerformed

    private void AtualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarBtnActionPerformed
        atualizar_produtos();
    }//GEN-LAST:event_AtualizarBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        cdtxt.requestFocus();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImprimirIreport.thisMov(movimento - 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //JOptionPane.showMessageDialog(null, "Closing");
    }//GEN-LAST:event_formWindowClosing

    private void sangriaSuprimentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sangriaSuprimentoBtnActionPerformed
        if (usuario.isPrivilegio()) {
            seletorSangriaSuprimento();
        }else{
            JD_Autorizar jd = new JD_Autorizar(null, true);
            jd.setVisible(true);
            if (jd.getUsuario_autorizado()!=null){
                seletorSangriaSuprimento();
            }
        }
    }//GEN-LAST:event_sangriaSuprimentoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_PDV(new Usuario_DAO().getUsuario("jonathan"), new Caixa_DAO().getCaixaAberto()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarBtn;
    private javax.swing.JButton BuscaBtn;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JTextField cdtxt;
    private javax.swing.JTextField desctxt;
    private javax.swing.JButton finalizarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel movtxt;
    private javax.swing.JTextField qtdtxt;
    private javax.swing.JButton sangriaSuprimentoBtn;
    private javax.swing.JLabel usertxt;
    private javax.swing.JTextField valorTotallbl;
    // End of variables declaration//GEN-END:variables

    private void ini() {
        try {
            clientes = new Cliente_DAO().findAll();
        } catch (Exception ex) {
            Logger.getLogger(JF_PDV.class.getName()).log(Level.SEVERE, null, ex);
        }
        produtos = new Produto_DAO().findAll();
        tb = (DefaultTableModel) jTable1.getModel();
        this.setExtendedState(JF_PDV.MAXIMIZED_BOTH);
        cdtxt.requestFocus();
        atualizarMovimento();
        usertxt.setText(usuario.getNome());
    }

    private void atualizarTotal() {
        double soma = 0;
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            soma += (double) jTable1.getValueAt(x, 5);
        }
        totalAberto = Conv.CDblDuasCasas(soma);
        valorTotallbl.setText(Conv.validarValue(soma));
    }

    private void incluir_na_tabela() {
        for (Produto_Bean p : produtos) {
            if (p.getCodigo().equals(cdtxt.getText())) {
                double qtd;
                try {
                    qtd = Double.parseDouble(qtdtxt.getText().replaceAll(",", "\\."));
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Quantidade inválida!");
                    return;
                }
                Object[] dado = {jTable1.getRowCount() + 1, p.getDescricao(), p.getCodigo(), qtd, p.getVenda(), qtd * p.getVenda()};
                tb.addRow(dado);
                atualizarCount();
                desctxt.setText(p.getDescricao());
                cdtxt.setText("");
                qtdtxt.setText("1");
                cdtxt.requestFocus();
                atualizarTotal();
                ScroollJTable.scroollAutoEnd(jTable1);
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Produto nao cadastrado!");
        cdtxt.setText("");
        qtdtxt.setText("1");
        cdtxt.requestFocus();
    }

    private void excluir_item() {
        if (jTable1.getRowCount() > 0) {
            if (!usuario.isPrivilegio()){
                JD_Autorizar jd = new JD_Autorizar(null, true);
                jd.setVisible(true);
                if (jd.getUsuario_autorizado()==null){
                    return;
                }
            }
            JD_CancelarItemPDV jd = new JD_CancelarItemPDV(null, true);
            jd.setVisible(true);
            switch (jd.op) {
                case 1:
                    if (jTable1.getRowCount() > 0) {
                        tb.removeRow(tb.getRowCount() - 1);
                    }
                    break;
                case 2:
                    if (jTable1.getSelectedRow() >= 0) {
                        tb.removeRow(jTable1.getSelectedRow());
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecione um item na lista para ser excluido.");
                    }
                    break;
                case 3:
                    int op = -1;
                    op = JOptionPane.showOptionDialog(null, "Deseja realmente cancelar tudo?", "Cancelar Tudo", JOptionPane.YES_NO_CANCEL_OPTION, op, null, null, null);
                    if (op == 0) {
                        reiniciar();
                    }
                    break;
                default:
                    break;
            }
            cdtxt.requestFocus();
            atualizarTotal();
            atualizarCount();
        }
    }

    private void buscar() {
        JD_ProcurarItemPDV jd = new JD_ProcurarItemPDV(null, true);
        jd.setVisible(true);
        if (jd.p.getCodigo() != null) {
            cdtxt.setText(jd.p.getCodigo());
        }
        cdtxt.requestFocus();
    }

    private void atualizar_produtos() {
        produtos = new Produto_DAO().findAll();
        JOptionPane.showMessageDialog(null, "Atualizado!");
        cdtxt.requestFocus();
    }

    private void atualizarMovimento() {
        movimento = new Venda_DAO().getMovimentoLivre();
        movtxt.setText(Integer.toString(movimento));
    }

    private void finalizar() {
        if (jTable1.getRowCount() > 0) {
            JD_FinalizarCompraPDV jd = new JD_FinalizarCompraPDV(null, true, totalAberto, tb, movimento, caixa.getSeq());
            jd.setVisible(true);
            if (jd.fim == 1) {
                reiniciar();
            }
        }
    }

    private void atualizarCount() {
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            jTable1.setValueAt(x + 1, x, 0);
        }

    }

    private void reiniciar() {
        tb.setRowCount(0);
        valorTotallbl.setText("0,00");
        desctxt.setText("");
        cdtxt.requestFocus();
        atualizarMovimento();
    }

    private void iniciar_PDV() {
        try {
            ip_conectado = InetAddress.getLocalHost().getHostAddress();
        } catch (UnknownHostException ex) {
            Logger.getLogger(JF_PDV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void seletorSangriaSuprimento() {
        JD_Seletor_Sangria_Suprimento jd = new JD_Seletor_Sangria_Suprimento(null, true);
        jd.setVisible(true);
        if (jd.isSangria()) {
            JD_Sangria jd2 = new JD_Sangria(null, true);
            jd2.setVisible(true);
            if (jd2.getValor()>0){
                if (!new Caixa_DAO().fazerSangria(jd2.getValor(), caixa.getSeq())){
                    JOptionPane.showMessageDialog(null, "Erro ao tentar fazer sangria.","Erro",JOptionPane.WARNING_MESSAGE);
                }
            }
        } else if (jd.isSuprimento()) {
            JD_Suprimento jd2 = new JD_Suprimento(null, true);
            jd2.setVisible(true);
            if (jd2.getValor()>0){
                if (!new Caixa_DAO().colocarSuprimento(jd2.getValor(), caixa.getSeq())){
                    JOptionPane.showMessageDialog(null, "Erro ao tentar inserir suprimento.","Erro",JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }
}
