/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.Oprincipio.Produto;

import br.Oprincipio.Movimento.JD_Movimento;
import br.Oprincipio.Bean.Venda_Bean;
import br.Oprincipio.DAO.Venda_DAO;
import br.Oprincipio.Bean.Combo_Bean;
import br.Oprincipio.Bean.Produto_Bean;
import br.Oprincipio.DAO.Produto_DAO;
import funcoes.CDate;
import funcoes.Conv;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class JF_CadastroCombo extends javax.swing.JFrame {

    DefaultTableModel tb;
    List<Produto_Bean> produtos;
    boolean existe;
    //private Produto_Bean produto;
    private Combo_Bean combo;

    /**
     * Creates new form Combo_JF
     *
     * @param combo
     */
    public JF_CadastroCombo(Combo_Bean combo) {
        this.combo = combo;
        initComponents();
        ini();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lucrolbl = new javax.swing.JLabel();
        vendalbl = new javax.swing.JLabel();
        vendatf = new javax.swing.JTextField();
        cd_tf = new javax.swing.JTextField();
        cdlbl = new javax.swing.JLabel();
        desclbl = new javax.swing.JLabel();
        custolbl = new javax.swing.JLabel();
        custotf = new javax.swing.JTextField();
        desctf = new javax.swing.JTextField();
        lucrotf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cdInternotxt = new javax.swing.JTextField();
        novolbl = new javax.swing.JLabel();
        procurarlbl = new javax.swing.JLabel();
        gravarlbl = new javax.swing.JLabel();
        cancelarlbl = new javax.swing.JLabel();
        excluirlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        data1 = new javax.swing.JFormattedTextField();
        data2 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        qtdtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Combo");

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lucrolbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lucrolbl.setText("Margem Lucro%");

        vendalbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vendalbl.setText("Venda");

        vendatf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendatfActionPerformed(evt);
            }
        });
        vendatf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vendatfKeyPressed(evt);
            }
        });

        cd_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cd_tfKeyPressed(evt);
            }
        });

        cdlbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cdlbl.setText("Código");

        desclbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        desclbl.setText("Descrição");

        custolbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        custolbl.setText("Custo");

        custotf.setEditable(false);
        custotf.setText("0.0");
        custotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custotfActionPerformed(evt);
            }
        });
        custotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                custotfKeyPressed(evt);
            }
        });

        desctf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desctfActionPerformed(evt);
            }
        });
        desctf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                desctfKeyPressed(evt);
            }
        });

        lucrotf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lucrotfKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CD Interno");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(cdInternotxt))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cd_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(desctf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(custotf)
                                    .addComponent(custolbl, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lucrotf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lucrolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vendalbl, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(vendatf)))
                            .addComponent(desclbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cdInternotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cdlbl)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cd_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(desclbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desctf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(vendalbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vendatf, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(custolbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custotf))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lucrolbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lucrotf)))
                .addGap(32, 32, 32))
        );

        novolbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        novolbl.setForeground(new java.awt.Color(255, 255, 255));
        novolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        novolbl.setText("Novo");
        novolbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novolblMouseClicked(evt);
            }
        });

        procurarlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        procurarlbl.setForeground(new java.awt.Color(255, 255, 255));
        procurarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procurarlbl.setText("Procurar");
        procurarlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                procurarlblMouseClicked(evt);
            }
        });

        gravarlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gravarlbl.setForeground(new java.awt.Color(255, 255, 255));
        gravarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gravarlbl.setText("Gravar");
        gravarlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gravarlblMouseClicked(evt);
            }
        });

        cancelarlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelarlbl.setForeground(new java.awt.Color(255, 255, 255));
        cancelarlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarlbl.setText("Cancelar");
        cancelarlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarlblMouseClicked(evt);
            }
        });

        excluirlbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        excluirlbl.setForeground(new java.awt.Color(255, 255, 255));
        excluirlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        excluirlbl.setText("Excluir");
        excluirlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirlblMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Incluir");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Remover");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Descrição", "Quantidade", "Custo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(3).setMinWidth(60);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(60);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(novolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(procurarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gravarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(cancelarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(excluirlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procurarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gravarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Geral", jPanel1);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movimento", "QTD", "Cliente", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Data Inicial");

        jLabel5.setText("Data Final");

        try {
            data1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data1.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        try {
            data2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data2.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        qtdtxt.setText("Quantidade vendida no período");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(172, 172, 172))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(qtdtxt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdtxt)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hist. Saída", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void desctfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desctfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            vendatf.requestFocus();
        }
    }//GEN-LAST:event_desctfKeyPressed

    private void cd_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cd_tfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            desctf.requestFocus();
        }
    }//GEN-LAST:event_cd_tfKeyPressed

    private void vendatfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vendatfKeyPressed
        atualizarCusto();
    }//GEN-LAST:event_vendatfKeyPressed

    private void custotfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custotfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            lucrotf.requestFocus();
        }
    }//GEN-LAST:event_custotfKeyPressed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        if (jTable1.getRowCount() > 0) {
            atualizarCusto();
        }
    }//GEN-LAST:event_jTable1PropertyChange

    private void lucrotfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lucrotfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double custo = Double.parseDouble(custotf.getText().replaceAll(",", "\\."));
            double margem = Double.parseDouble(lucrotf.getText().replaceAll(",", "\\."));
            margem = margem / 100 + 1;
            vendatf.setText(Double.toString(Conv.CDblDuasCasas(custo * margem)));
            vendatf.requestFocus();
        }
    }//GEN-LAST:event_lucrotfKeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if (jTable2.getSelectedRow() < 0) {
            return;
        }
        if (evt.getClickCount() == 2) {
            ver_movimento();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        atualizarHistTB();
    }//GEN-LAST:event_jPanel3FocusGained

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        if (jTabbedPane1.getSelectedIndex() == 1) {
            data1.setText(CDate.DataPTBRAtual());
            data2.setText(CDate.DataPTBRAtual());
            atualizarHistTB();
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void novolblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novolblMouseClicked
        novoBtn();
    }//GEN-LAST:event_novolblMouseClicked

    private void procurarlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_procurarlblMouseClicked
        procurarBtn();
    }//GEN-LAST:event_procurarlblMouseClicked

    private void gravarlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gravarlblMouseClicked
        gravarBtn();
    }//GEN-LAST:event_gravarlblMouseClicked

    private void cancelarlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarlblMouseClicked
        cancelarBtn();
    }//GEN-LAST:event_cancelarlblMouseClicked

    private void excluirlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirlblMouseClicked
        excluirBtn();
    }//GEN-LAST:event_excluirlblMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        incluirProdutos();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        removerProduto();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void vendatfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendatfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendatfActionPerformed

    private void custotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custotfActionPerformed

    private void desctfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desctfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desctfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_CadastroCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_CadastroCombo(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelarlbl;
    private javax.swing.JTextField cdInternotxt;
    private javax.swing.JTextField cd_tf;
    private javax.swing.JLabel cdlbl;
    private javax.swing.JLabel custolbl;
    private javax.swing.JTextField custotf;
    private javax.swing.JFormattedTextField data1;
    private javax.swing.JFormattedTextField data2;
    private javax.swing.JLabel desclbl;
    private javax.swing.JTextField desctf;
    private javax.swing.JLabel excluirlbl;
    private javax.swing.JLabel gravarlbl;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lucrolbl;
    private javax.swing.JTextField lucrotf;
    private javax.swing.JLabel novolbl;
    private javax.swing.JLabel procurarlbl;
    private javax.swing.JLabel qtdtxt;
    private javax.swing.JLabel vendalbl;
    private javax.swing.JTextField vendatf;
    // End of variables declaration//GEN-END:variables
    private void ini() {
        tb = (DefaultTableModel) jTable1.getModel();
        //produtos = new Produto_DAO().findAll();
        cdInternotxt.setEnabled(false);
        cancelarBtn();
        setStatusLbl(false);
        verificaSeExiste();
    }

    private void setStatusBtn(boolean status) {
        novolbl.setVisible(status);
        procurarlbl.setVisible(status);
        gravarlbl.setVisible(status);
        cancelarlbl.setVisible(status);
        excluirlbl.setVisible(status);
    }

    private void novoBtn() {
        setStatusBtn(false);
        gravarlbl.setVisible(true);
        cancelarlbl.setVisible(true);
        int max = new Produto_DAO().getMaxID() + 1;
        cdInternotxt.setText(Integer.toString(max));
        setStatusLbl(true);
        cd_tf.requestFocus();
        custotf.setText("0.0");
    }

    private void procurarBtn() {
        JD_BuscarProduto jd = new JD_BuscarProduto(null, true, 2);
        jd.setVisible(true);
        if (jd.p != null) {
            combo = new Produto_DAO().getCombo(jd.p.getCodigo(), jd.p.getDescricao(), jd.p.getId(), jd.p.getVenda(), jd.p.getMargem());
            verificaSeExiste();
        }
    }

    private void cancelarBtn() {
        setStatusBtn(false);
        novolbl.setVisible(true);
        procurarlbl.setVisible(true);
        setStatusLbl(false);
        limparLbl();
        tb.setRowCount(0);
    }

    private void excluirBtn() {
        if (existe) {
            int op = -1;
            op = JOptionPane.showOptionDialog(null, "Deseja realmente Excluir Esse Combo?", "Exclusão Segura", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
            if (op == 0) {
                if (new Produto_DAO().delete(Integer.parseInt(cdInternotxt.getText()), cd_tf.getText())) {
                    JOptionPane.showMessageDialog(null, "Combo excluido com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao tentar exluir o Combo do banco de dados!");
                }
            }
        }
        cancelarBtn();
    }

    private void setStatusLbl(boolean status) {
        cd_tf.setEnabled(status);
        desctf.setEnabled(status);
        custotf.setEnabled(status);
        lucrotf.setEnabled(status);
        vendatf.setEnabled(status);
    }

    private void gravarBtn() {
        if (jTable1.getRowCount()==0){
            int op = -1;
            op = JOptionPane.showOptionDialog(null, "Por não conter itens no 'combo' o mesmo será cadastrado como produto!\nDeseja confirmar?", "Alteração de tipo", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
            if (op!=0){
                return;
            }
        }
        try {
            Combo_Bean c = new Combo_Bean();
            c.setId(Integer.parseInt(cdInternotxt.getText()));
            c.setCd(cd_tf.getText());
            c.setDescricao(desctf.getText());
            if (!lucrotf.getText().equals("")) {
                c.setMargem(Conv.CDblDuasCasas(Double.parseDouble(lucrotf.getText().replaceAll(",", "\\."))));
            }
            if (!vendatf.getText().equals("")) {
                c.setValor(Conv.CDblDuasCasas(Double.parseDouble(vendatf.getText().replaceAll(",", "\\."))));
            }
            produtos = new ArrayList<>();
            for (int x = 0; x < tb.getRowCount(); x++) {
                Produto_Bean pp = new Produto_DAO().getProduto_ID((int) tb.getValueAt(x, 0));
                pp.setQuantidade((double) jTable1.getValueAt(x, 3));
                produtos.add(pp);
            }
            c.setProdutos(produtos);
            if (!existe) {
                if (new Produto_DAO().insertInto(c)) {
                    JOptionPane.showMessageDialog(null, "Combo Cadastrado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar o Combo!");
                }
            } else if (existe) {
                if (new Produto_DAO().update(c)) {
                    JOptionPane.showMessageDialog(null, "Produto Atualizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao atualizar o Produto!");
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(JF_CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        cancelarBtn();
    }

    private void limparLbl() {
        cd_tf.setText("");
        desctf.setText("");
        custotf.setText("");
        lucrotf.setText("");
        vendatf.setText("");
    }

    private void verificaSeExiste() {
        if (combo != null) {
            existe = true;
            setStatusLbl(existe);
            cdInternotxt.setText(Integer.toString(combo.getId()));
            cd_tf.setText(combo.getCd());
            desctf.setText(combo.getDescricao());
            lucrotf.setText(Double.toString(combo.getMargem()));
            vendatf.setText(Double.toString(combo.getValor()));
            setStatusBtn(false);
            gravarlbl.setVisible(true);
            cancelarlbl.setVisible(true);
            excluirlbl.setVisible(true);
            custotf.setText("0.00");
            tb.setRowCount(0);
            for (Produto_Bean p : combo.getProdutos()) {
                Object[] dado = {p.getId(), p.getCodigo(), p.getDescricao(), p.getQuantidade(), p.getCusto()};
                tb.addRow(dado);
            }
            atualizarCusto();
        }
    }

    private void incluirProdutos() {
        JD_BuscarProduto jd = new JD_BuscarProduto(null, true, JD_BuscarProduto.PRODUTO);
        jd.setVisible(true);
        if (jd.p != null) {
            Produto_Bean p = jd.p;
            Object[] dado = {p.getId(), p.getCodigo(), p.getDescricao(), 1.0, p.getCusto()};
            tb.addRow(dado);
        }
        atualizarCusto();
    }

    private void removerProduto() {
        if (jTable1.getSelectedRow() < 0) {
            return;
        }
        tb.removeRow(jTable1.getSelectedRow());
        atualizarCusto();
    }

    private void atualizarCusto() {
        double custo = 0;
        for (int x = 0; x < jTable1.getRowCount(); x++) {
            double linha = (double) tb.getValueAt(x, 3) * (double) tb.getValueAt(x, 4);
            custo += linha;
        }
        custotf.setText(Conv.validarValue(custo));
        try {
            custo = Double.parseDouble(custotf.getText().replaceAll(",", "\\."));
            double venda = Double.parseDouble(vendatf.getText().replaceAll(",", "\\."));
            lucrotf.setText(Double.toString(Conv.CDblDuasCasas(((venda / custo) - 1) * 100)));
        } catch (Exception ex) {

        }
    }

    private void atualizarHistTB() {
        List<Venda_Bean> ven = new Venda_DAO().histVendaProduto(cd_tf.getText());
        DefaultTableModel tb2 = (DefaultTableModel) jTable2.getModel();
        tb2.setRowCount(0);
        for (Venda_Bean v : ven) {
            Object[] dado = {v.getMovimento(), v.getProdutos().get(0).getQuantidade(), v.getCliente().getNome(), v.getData()};
            tb2.addRow(dado);
        }
        atualizarQtdVenda();
    }

    private void buscar() {
        atualizarHistTB();
        if (data1.getText().equals("  /  /    ") || data2.getText().equals("  /  /    ")) {
            return;
        }
        DefaultTableModel tb2 = (DefaultTableModel) jTable2.getModel();
        try {
            Date d1 = CDate.DataPTBRStringToDate(data1.getText());
            Date d2 = CDate.DataPTBRStringToDate(data2.getText());
            for (int x = 0; x < jTable2.getRowCount(); x++) {
                Date d3 = CDate.DataPTBRStringToDate((String) jTable2.getValueAt(x, 3));
                if (d3.before(d1) || d3.after(d2)) {
                    tb2.removeRow(x);
                    x--;
                }
            }
            atualizarQtdVenda();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "As Datas 'Inicial' e 'Final' precisam ser preenchidas corretamente!");
        }
    }

    private void atualizarQtdVenda() {
        double qtd = 0;
        for (int x = 0; x < jTable2.getRowCount(); x++) {
            qtd += (double) jTable2.getValueAt(x, 1);
        }
        qtdtxt.setText("Quantidade vendida no período: " + qtd);
    }

    private void ver_movimento() {
        int mov = (int) jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        Venda_Bean venda = new Venda_DAO().getVenda(mov);
        JD_Movimento jd = new JD_Movimento(this, true, venda);
        jd.setVisible(true);
    }
}
